volumes:
  ckan_pycsw_logs:
  ckan_pycsw_metadata:

services:
  ckan2pycsw:
    container_name: ckan-pycsw
    build:
      context: .
      dockerfile: ckan-pycsw/Dockerfile.ghcr
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - "0.0.0.0:${PYCSW_PORT}:${PYCSW_PORT}"
    volumes:
        - ckan_pycsw_logs:${APP_DIR}/log
        - ckan_pycsw_metadata:${APP_DIR}/metadata
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:${PYCSW_PORT}"]
networks:
  default:
    name: ckan2pycsw_default