version: '3'

services:
  ckan2pycsw_test:
    container_name: ${CONTAINER_OS_NAME}
    build:
      context: .
      dockerfile: docker/${CONTAINER_OS}/${CONTAINER_OS}-${CONTAINER_OS_VERSION}/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - ${PYCSW_HOST_PORT}:${PYCSW_PORT}
      - ${SSH_HOST_PORT}:${SSH_PORT}
    volumes:
        - ./log:${APP_DIR}/ckan-pycsw/log
        - ./metadata:${APP_DIR}/ckan-pycsw/metadata
networks:
  default:
    name: ckan2pycsw-test