volumes:
  ckan_pycsw_logs:
  ckan_pycsw_metadata:

services:
  ckan2pycsw_test:
    container_name: ${CONTAINER_OS_NAME}
    build:
      context: .
      dockerfile: docker/${CONTAINER_OS}/${CONTAINER_OS}-${CONTAINER_OS_VERSION}/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - ${PYCSW_HOST_PORT}:${PYCSW_PORT}
      - ${SSH_HOST_PORT}:${SSH_PORT}
    volumes:
        - ckan_pycsw_logs:${APP_DIR}/log
        - ckan_pycsw_metadata:${APP_DIR}/metadata
networks:
  default:
    name: ckan2pycsw-test